name = "agent-briefing-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "AGENT_BRIEFING_KV"
id = "89d77de03f8845dd95aac35c1aa2cc2f"
preview_id = "178cdbfd677d4cfeb3a520abd7414778"

[[r2_buckets]]
binding = "BRIEFING_FILES"
bucket_name = "agent-briefing-files"
preview_bucket_name = "agent-briefing-files-preview"

[ai]
binding = "AI"

[build]
command = ""

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"
